### ISSUE TITLE
Unknown Hard Crashes

### ISSUE THREAD

**Issue by AttiiSan** [ArchiDog1998/RotationSolver#103]
Keeps happening while trying to log in. Also crashes when trying to install. Tried with and without other plugins too.

**Comment by ArchiDog1998** [comment]
Oh, God! Let me see...

**Comment by ArchiDog1998** [comment]
I just tried to login again, without crashes. Is it only in the version 1.2.2? I guess it may be caused by the highlighting of the Crossbar added in the new version, but I'm not sure.

**Comment by AttiiSan** [comment]
Yeah, it started happening when I updated to 1.2.2 version. Doesnt give me an log file or error codes. Just a window pops up and says "Unknown Hard Crash"

**Comment by AttiiSan** [comment]
I just tried deleting config files and reinstalled it. Worked this time. I wonder if another plugin could be causing this. XIVcombo or something maybe?

**Comment by AttiiSan** [comment]
Just confirmed. SimpleTweaks and this have a problem with each other.

**Comment by ArchiDog1998** [comment]
Sorry for late answer. I installed the SimpleTweak too, but I don't have this problem. I think it is caused by reading config files using jsonConverter. I'll add a try catch on it.

**Comment by AttiiSan** [comment]
I wondered if a certain feature/setting in SimpleTweaks could be culprit. Im no expert though. Just figured Id let you know what was happening on my end.

**Comment by ArchiDog1998** [comment]
Thanks for your feedback. I'll pay attention to it.

**Comment by AttiiSan** [comment]
Figured it out. The simpletweaks command for blocking treasure hunt enemies was causing it. Makes sense since your plugin can target automatically and that simple tweak will block targeting for a specific mob. Just thought I'd update you on my find.

**Comment by ArchiDog1998** [comment]
Wow. It is a nice feature. Could you tell me the name of the check box of this feature? I think I can add the treasure hunt target strategy into Rotation Solver.

**Comment by AttiiSan** [comment]
The name of the checkbox feature is under the General Tab and its called "Block Targeting Treasure Hunt Enemies." Its one of the first check boxes in that tab.

**Comment by ArchiDog1998** [comment]
Thank you! I'll check it.
