### ISSUE TITLE
Dancer bug

### ISSUE THREAD

**Issue by Constmar** [ArchiDog1998/RotationSolver#104]
Dancer double standard finish and quadruple technical finish/tillana are not triggering after today's update when using the manual/auto mode, is it just me, did i mess something up or is anyone having this problem aswell?

**Comment by ArchiDog1998** [comment]
I don't have a max-level dancer, so I can't test it. But my update yesterday doesn't seem to affect this feature. I hope others can check it. Besides, it is better to raise an issue on discord DNC channel.

**Comment by Constmar** [comment]
ok, i'll post there right now, thank you!
