### ISSUE TITLE
FPS Tanks when job is set to Blue Mage.

### ISSUE THREAD

**Issue by imgidedin** [ArchiDog1998/RotationSolver#110]
My FPS goes from 120 to 18 when having Blue Mage job active. Disabling Blue mage on the Ranged Magical just makes it goes up to 27. Never noticed it before and it happened before today's update (as I updated it to see if it would fix).

WIth Rotation enabled and Blue Mage disabled: 
![image](https://user-images.githubusercontent.com/19570528/216041418-a1703bfe-3199-4584-a377-b336c1c3ff3c.png)
With Rotation Disabled: 
![image](https://user-images.githubusercontent.com/19570528/216041479-51c622bf-c509-473a-905c-7a590a2940c0.png)
Rotation Enabled and Blue Mage enabled: 
![image](https://user-images.githubusercontent.com/19570528/216041565-0e2795b2-b030-4d4c-8f4f-0eeabd84f745.png)

**Comment by ArchiDog1998** [comment]
Well. Mine is from 70 to 60. I don't know why. Today's update, I add a multi-thread feature for acceleration. Actually, jobs' rotation calculation is on the work task.

**Comment by imgidedin** [comment]
Dont know what you changed, but it is working as intended now on the last update.
