### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ArmoredPuma** [ArchiDog1998/RotationSolver#130]
It seems when i have this addon enabled it auto crashes my game. I have to manually remove it from the quick launcher or i cant get into the game at all

**Comment by ArmoredPuma** [comment]
I can grab it for you sure! Where would i find that for you? :)

**Comment by ArchiDog1998** [comment]
`C:\Users\%USERNAME%\AppData\Roaming\XIVLauncher\dalamud.log`
After crashing, please send this file to me in any way. Thanks.

**Comment by ArmoredPuma** [comment]
So i actually found the problem myself, it seems if i try to run the addon simple tweaks it is what causes it to crash

**Comment by ArchiDog1998** [comment]
Uhh. I'm also using Simple Tweaks. It is a big plugin, I don't know which feature is conflicting with this plugin.

**Comment by ArmoredPuma** [comment]
honestly i like yours way more so i just disabled Simple Tweaks ahha
