### ISSUE TITLE
Additions

### ISSUE THREAD

**Issue by adambennett55** [ArchiDog1998/RotationSolver#156]
Would it be possible to Add a few more options:

1 - checkbox to turn off when dead --> currently automatically does (could it just pause the routine while dead and resume a few seconds after alive)

2 - checkbox to turn off during cut scenes  --> currently automatically does (could it just pause the routine while in a cut scene and resume after)

Also could you look at Bard's Rain of Death, its not very consistent, I'm not sure what logic it is using, but it should Cast it whenever there are 2 or more mobs in range (25y) of the mob you are targeting.

**Comment by ArchiDog1998** [comment]
Thank you. I'll add these two options in the next version. Besides `turn off during cut scenes` is bound with `turn off when territory changed`. So, you can turn off that one to achieve your goal. And I'll split them to two options.

And the action `Rain of Death` will be used when the number of targets is more or equals to two.

**Comment by adambennett55** [comment]
Well I do have the open to not shut off for territory change and it works but it still shuts off during cut scenes

**Comment by ArchiDog1998** [comment]
Oh, it'll be off when duty end! I'll remove that.

**Comment by Spacellary** [comment]
@ArchiDog1998
Sorry for being off-topic here...
Just using this opportunity to sing you some praise, Archi you're one of the most active and quick plugin developers I've ever seen. My friend, you are impressive! And also, your C# code is beautiful.
👏 🏆
