### ISSUE TITLE
/rotation Manual chooses the target automatically

### ISSUE THREAD

**Issue by V3semir** [ArchiDog1998/RotationSolver#160]
As in title, before the today's update, it would let me choose the target, but now it's acting like the "/rotation Smart". No matter I'm in combat or not, it would attack the hostile target automatically. Tried to reset settings, but it didn't help.

**Comment by ArchiDog1998** [comment]
Thanks! I figured out why and fixed it! https://github.com/ArchiDog1998/RotationSolver/commit/af13b96c6a05bb67e15fc488bbaf48f9a98c992e
