### ISSUE TITLE
Every time you update, dalamud crashes on game start.

### ISSUE THREAD

**Issue by Kumicoo** [ArchiDog1998/RotationSolver#206]
Hey.

Every time there is an update, the game is unable to start, it always crashes and i have to completely reinstall rotation solver.

What is going on?

It wasnt like this some months ago.

Want logs?

**Comment by ArchiDog1998** [comment]
Sorry. I know it is a bad Image exception. Because I updated the rotations file.
It fixed now.

**Comment by ArchiDog1998** [comment]
Because this plug-in is not only a local plug-in, but also online. There are still many issues to be identified.
