### ISSUE TITLE
After Update, all rotations are "Invalid".

### ISSUE THREAD

**Issue by Kumicoo** [ArchiDog1998/RotationSolver#224]
After your update today, it doesnt work again. Every rotation is marked as "Invalid."
![image](https://user-images.githubusercontent.com/35538818/232495677-91fd6337-a0a5-445e-b222-71ae56d96db5.png)

**Comment by ArchiDog1998** [comment]
Yeah, I found it. https://discord.com/channels/1064448004498653245/1064733738187096155/1097492110934024222
https://github.com/ArchiDog1998/RotationSolver/commit/290476b097370e1d53f43881929056f1831bc8c4
This error will not affect your use of it. It'll be fixed in the next version.
