### ISSUE TITLE
Rotations are tagged as "Invalid".

### ISSUE THREAD

**Issue by GrndFress** [ArchiDog1998/RotationSolver#293]
Since v2.8.0 was released, every rotation has been tagged as "Invalid" and is not working.
![Screenshot_11](https://github.com/ArchiDog1998/RotationSolver/assets/133194174/d300217c-b787-4837-9767-68f8c08cb68e)

**Comment by RemiliaSCLT** [comment]
same here too

**Comment by GrndFress** [comment]
Oh, Thank you for the update! If i manually downgrade the plugin, will it auto update, once this bug gets fixed or will i have to delete the "downgraded" version and download the new fixed version manually? Either way, thank you for the update.

**Comment by Niahmi** [comment]
> Oh, Thank you for the update! If i manually downgrade the plugin, will it auto update, once this bug gets fixed or will i have to delete the "downgraded" version and download the new fixed version manually? Either way, thank you for the update.

Once a new version is posted, you can update the plugin as per usual. Don't update the plugin after doing this though until the new version comes out, or you'll likely have to repeat the above steps.

**Comment by GrndFress** [comment]
Got it. Once again, thank you for the update, wishing you and ArchiDog the best.
