### ISSUE TITLE
WHM using pre regen no matter if option is on or not

### ISSUE THREAD

**Issue by gavsloth** [ArchiDog1998/RotationSolver#359]
White mage uses pre regen no matter if It's on or not, I may just be misinterpeting the setting.

**Comment by ArchiDog1998** [comment]
https://github.com/ArchiDog1998/FFXIVRotations/blob/a2ee3fbfc13c909d856ddb5d740456a481fe8c35/DefaultRotations/Healer/WHM_Default.cs#L13
There is an option about pre regen in config.

**Comment by gavsloth** [comment]
Thank you, I think I am just misinterpeting it but it seems that even when the setting is off it still uses pre regen

**Comment by gavsloth** [comment]
Nevermind I am wrong thank you!
