### ISSUE TITLE
Feature request: Enable use of variant actions

### ISSUE THREAD

**Issue by Flavescent** [ArchiDog1998/RotationSolver#393]
I'd appreciate it if anyone could look into adding variant actions (used in variant dungeons such as Mount Rokkon) to the official rotations.

The way SlothCombo handles them is:

- Spirit Dart (Tank/Healer): Use if debuff is not present or less than 3 s
- Variant Cure (Tank/DPS): Use if HP is below user-set threshold
- Variant Ultimatum (Tank): used on cooldown
- Variant Rampart (Healer/DPS): used on cooldown

**Comment by Flavescent** [comment]
Thank you for the very fast fix! I have tested them with a MCH in both variant dungeons, using Variant Cure and Variant Rampart.

In the Sil'dihn Subterrane, the variant actions work as expected.

But in Mount Rokkon, the variant actions are not used by the rotation. This may be because there they apparently have different internal IDs there. [This fix in SlothCombo](https://github.com/Nik-Potokar/XIVSlothCombo/commit/4c0da8c52c0cc232f351d93de5939b9cc4a48a5a), which addressed the same bug, may help in this regard.

**Comment by ArchiDog1998** [comment]
Yeah, I see. They are different ids. I added them.

**Comment by Flavescent** [comment]
Thank you again! Unfortunately, when I tried to test this again after today's 6.48 update, Variant Cure and Variant Rampart are not used in either variant dungeon. Maybe the update broke the IDs / opcodes?

**Comment by ArchiDog1998** [comment]
Sorry, I can't test on it.
