### ISSUE TITLE
Feature request: Dismount upon engagement

### ISSUE THREAD

**Issue by Flavescent** [ArchiDog1998/RotationSolver#394]
Hi, I think it would be helpful to add a feature to attempt to dismount if the player is mounted when a target is engaged. This would help with attacking hunt train targets directly from the air, so to speak.

**Comment by ArchiDog1998** [comment]
Hi, sorry for the delay. This feature doesn't sound like a part of the rotation. I think it fits [Pandora's Box](https://github.com/PunishXIV/PandorasBox) better.

**Comment by Flavescent** [comment]
Thank you! I do in fact use a plugin that dismounts me when the a combat ability is attempted to be used (though I can't determine which of my many plugins does this... I can't find the option in Pandora). But since Rotation Solver does not appear to attempt to use combat abilities while the player is mounted, the plugin does nothing when used in conjunction with RS. 

Indeed, since RS does nothing when activated while mounted, I can't really see how another plugin could even recognize that RS wants to fight and dismount the player. One option would be to add an option to allow RS to use actions while mounted so that other plugins can act on them. Another would be to add the dismount functionality to RS itself. 

Of course, you may want to do neither, which I would completely understand, since it's a very, very minor QoL thing.

**Comment by ArchiDog1998** [comment]
Well, for me, this feature request is like this: If the player is engaged and is on the mount and it is not very high from the territory, then dismount. 

If the player is not on the mount and engaged, the RS'll automatically do a rotation for you.

And yes, Pandora doesn't have this feature now. But this feature fits Pandora more than RS. RS focuses on rotation itself. Pandora provides some parts to make your game experience better.

**Comment by Flavescent** [comment]
All right, thanks for looking into it!
