### ISSUE TITLE
RPR Rotation - Whorl of Death

### ISSUE THREAD

**Issue by jpostalwait** [ArchiDog1998/RotationSolver#399]
Having issue lately on Reaper, specifically with Whorl of Death.

Whorl of Death is never used in AOE situations. I have SCombo, Simple Tweaks, and Reaction disabled.
With SCombo enabled, only Whorl of Death is used - nothing else.

Any idea why Whorl of Death is never used?

**Comment by ArchiDog1998** [comment]
Please push this in discord.

**Comment by jpostalwait** [comment]
Ah, found a fix in the discord.
