### ISSUE TITLE
HighEndWarning Chat notification toggle

### ISSUE THREAD

**Issue by LuxLuma** [ArchiDog1998/RotationSolver#411]
The Chat notification `HighEndWarning` prints, to be more inline with the other notifications you can toggle.

https://github.com/thunderebolt/RotationSolver/blob/4f7aa829a2db633fc18a45f1ab16d7e96cb98daa/RotationSolver/Updaters/SocialUpdater.cs#L114-L140

Thanks

**Comment by ArchiDog1998** [comment]
Sorry, I don't understand. Do you need a toggle to disable this?

**Comment by LuxLuma** [comment]
Yes sorry that is what I mean thanks
