### ISSUE TITLE
help needed: Look for a way to hide Autorotation status

### ISSUE THREAD

**Issue by Waitsnake** [ArchiDog1998/RotationSolver#444]
Is there already an option, that I maybe have overseen, to hide the autorotation status that is left of the server name?
![autorotation_state_off](https://github.com/ArchiDog1998/RotationSolver/assets/942085/40c128e0-ad31-4f83-b84e-942eaa121f6b)

If there is no option to hide it, could this be a new feature request?

I actually not need the autorotation and just like to use the teaching mode to learn rotation better and like to have the UI as clean as possible.

**Comment by IncognitoWater** [comment]
Hi ! 
https://i.imgur.com/cv3F0Ny.png Inside UI->Information, you can uncheck Display plugin status on server info.
o/

**Comment by Waitsnake** [comment]
Ty for quick answer and sorry I was blind. 🙈
For some reason I only checked under UI the tabs Overlay and Windows and ignored Information completely. 😅
This ticket can be closed then.

**Comment by IncognitoWater** [comment]
No worries for that kind of question don't forget you can join the discord the community will help you the best they can, we are all very friendly. Link : https://discord.com/invite/4fECHunam9
