### ISSUE TITLE
Request: Some more Status IDs.

### ISSUE THREAD

**Issue by spaceelysian** [ArchiDog1998/RotationSolver#461]
Could you add the following status IDs? 

Gobskin = 2114
Toad Oil = 1737

Poison = 18
Breath of Magic = 3712
Mortal Flame = 3643

Thanks!

**Comment by ArchiDog1998** [comment]
Added. https://github.com/ArchiDog1998/RotationSolver/commit/a2040fad531d59788ce94d87bbbf8e5d61cda5b8
