### ISSUE TITLE
Standard Step & Technical step being automatically used when disabled

### ISSUE THREAD

**Issue by GrndFress** [ArchiDog1998/RotationSolver#513]
Hello. Im trying to use DNC with your great plugin but im having issue where "Standard Step" & "Technical step" are both being used automatically (During countdown and fight as well) even though both skills are disabled. Ive disabled the skills in the "Actions" but not sure if i have to disable it somewhere else as well in order to make it so its not used at all

**Comment by ArchiDog1998** [comment]
Thanks for your feedback! DNC one more! could you tell me what rotation are you using right now? I'll test it later.

**Comment by GrndFress** [comment]
Hey, Thank you for the fast response. Ive tried both rotations and it was being used automatically in both. I dont have enabled any other attack actions as well, only OGCD support actions

**Comment by GrndFress** [comment]
Ive also noticed that the finisher for both Standard Step & Technical step is being used 2s before the 15s (or any other) countodwn finishes, once again when both skills are disabled

**Comment by GrndFress** [comment]
New plugin version fixed it. Thank you for all your hard work on the plugin!
