### ISSUE TITLE
hi read

### ISSUE THREAD

**Issue by lucy2000** [ArchiDog1998/RotationSolver#582]
Hi i don't know else to reach your or if you have an email i can contact you on if you can send me something like discord lmk. 

M idea is have you thought of making a plugin similar to your rotation solver where it will move for you if you catch my drift

**Comment by ArchiDog1998** [comment]
Hi, there is no discord server for the Rotation Server. The discord server I created for RS was transferred to the Rotation Server Reborn Team.
Actually, the Rotation Solver focuses on the rotation itself, so the auto-moving feature is a side feature. It is better to add this feature to the plugins which focuses on moving!
However, there is a similar side feature in RS, it is in `Timeline`, and you can add a `Move Item` like that, you can preset the location that you want to move, it needs the plugin [ffxiv_navmesh](https://github.com/awgil/ffxiv_navmesh).

**Comment by lucy2000** [comment]
do you have a tutorial on how to use navmesh ?
