### ISSUE TITLE
Not Engaging FATE Targets

### ISSUE THREAD

**Issue by Piper19** [ArchiDog1998/RotationSolver#89]
This was observed as Summoner(37) using 'Smart HighHP' and 'Smart LowHP' auto-targeting. The result is the same when "Param>Target Selection>'Select only FATE targets'" option is both on and off.

The player is not automatically targetting or attacking FATE targets. Even when combat is initiated manually, the automatic rotation won't start. Player just stands idle after attacking once manually.

**Comment by ArchiDog1998** [comment]
Thanks for your feedback. I'll check it out. Besides, it is better to leave an issue on [Discord](https://discord.gg/4fECHunam9).

**Comment by ArchiDog1998** [comment]
I got it. The FateManager's FateJoined Property of Dalamud isn't worked fine.
