### ISSUE TITLE
Esuna not casting

### ISSUE THREAD

**Issue by Piper19** [ArchiDog1998/RotationSolver#90]
Observed as Sage, Scholar, and White Mage in dungeons Lv.70-90.  "Action>Support-GCD>Esuna" is enabled. Tested with "Rotation>Healer>SCH>Auto use GCD to heal" both on and off. The first few trash pulls in Haukke Manor were used to verify that it wasn't a configuration issue (Manor Maidservants cast 'Poison' on the MT). In that case, the player (Scholar) just continually casts Ruin and ignores the Poison debuff on MT. Ideally, an Esuna cast will have priority above damaging attacks from the player. 

I've only seen Esuna cast once. That was in [The Fell Court of Troia] (Doom debuff from Beatrice, the 2nd boss) while using Sage. But, the timing was both slow and illogical. It was weaved into the middle of the attack rotation.

**Comment by ArchiDog1998** [comment]
Thanks. Esuna will be used if the debuff is too dangerous, I listed a series of dangerous debuff there. If it is not on the list, you should use Esuna macro to tell the plugin to use Esuna. Besides, it is better to leave an issue on [Discord](https://discord.gg/4fECHunam9).
